################################################################################
#
# llvm-runtimes
#
################################################################################

LLVM_RUNTIMES_INITIAL_VERSION = $(LLVM_PROJECT_VERSION)
LLVM_RUNTIMES_INITIAL_SITE = $(LLVM_PROJECT_SITE)
LLVM_RUNTIMES_INITIAL_SOURCE = $(LLVM_PROJECT_SOURCE)
LLVM_RUNTIMES_INITIAL_DL_SUBDIR = llvm-project
LLVM_RUNTIMES_INITIAL_LICENSE = Apache-2.0 with exceptions, NCSA, MIT
LLVM_RUNTIMES_INITIAL_LICENSE_FILES = LICENSE.TXT
LLVM_RUNTIMES_INITIAL_CPE_ID_VENDOR = llvm
LLVM_RUNTIMES_INITIAL_SUPPORTS_IN_SOURCE_BUILD = NO
LLVM_RUNTIMES_INITIAL_INSTALL_STAGING = YES
LLVM_RUNTIMES_INITIAL_INSTALL_TARGET = NO
LLVM_RUNTIMES_INITIAL_SUBDIR = runtimes

LLVM_RUNTIMES_INITIAL_ADD_TOOLCHAIN_DEPENDENCY = NO

LLVM_RUNTIMES_INITIAL_DEPENDENCIES = host-clang host-lld musl-headers

LLVM_RUNTIMES_INITIAL_CMAKE_BACKEND = ninja

# The CMake toolchain file is normally installed by the completed toolchain.
# The bootstrap runtimes need it before the C library and toolchain exist.
LLVM_RUNTIMES_INITIAL_PRE_CONFIGURE_HOOKS += TOOLCHAIN_CMAKE_INSTALL_FILES

# Build LLVM runtimes based on selections
LLVM_RUNTIMES_INITIAL_LIST = compiler-rt libunwind

LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_ENABLE_RUNTIMES="$(subst $(space),;,$(LLVM_RUNTIMES_INITIAL_LIST))"

# Use native llvm-config from host-llvm if possible
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_NATIVE_TOOL_DIR=$(HOST_DIR)/bin

# Cross-compilation settings
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DCMAKE_CROSSCOMPILING=1
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_DEFAULT_TARGET_TRIPLE=$(GNU_TARGET_NAME)
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_BUILTIN_TARGETS=$(GNU_TARGET_NAME)
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_RUNTIME_TARGETS=$(GNU_TARGET_NAME)
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DLLVM_HOST_TRIPLE=$(GNU_TARGET_NAME)

# Compiler-rt specific settings (Disable all besides builtins)
LLVM_RUNTIMES_INITIAL_CONF_OPTS += -DCOMPILER_RT_DISABLE_AARCH64_FMV=OFF \
	-DCOMPILER_RT_BUILD_SANITIZERS=OFF \
	-DCOMPILER_RT_BUILD_XRAY=OFF \
	-DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
	-DCOMPILER_RT_BUILD_PROFILE=OFF \
	-DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
	-DCOMPILER_RT_BUILD_MEMPROF=OFF \
	-DCOMPILER_RT_BUILD_ORC=OFF \
	-DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
	-DCOMPILER_RT_USE_LLVM_UNWINDER=ON \
	-DLIBUNWIND_USE_COMPILER_RT=ON \
	-DLIBUNWIND_ENABLE_THREADS=OFF \
	-DLIBUNWIND_ENABLE_SHARED=OFF \
	-DLIBUNWIND_ENABLE_STATIC=ON \
	-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF

LLVM_RUNTIMES_INITIAL_CONF_OPTS += \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY

LLVM_RUNTIMES_INITIAL_CONF_OPTS += \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_DOCS=OFF \
	-DLLVM_BUILD_TESTS=OFF \
	-DLLVM_BUILD_EXAMPLES=OFF \
	-DLLVM_BUILD_DOCS=OFF

define LLVM_RUNTIMES_INITIAL_SETUP_COMPILER_RT_LIBS
	mkdir -p $(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/lib
	ln -snf ../../../../$(GNU_TARGET_NAME)/sysroot/usr/lib/linux \
		$(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/lib/linux
	ln -sf ../../../../$(GNU_TARGET_NAME)/sysroot/usr/share $(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/share
endef
LLVM_RUNTIMES_INITIAL_POST_INSTALL_STAGING_HOOKS += LLVM_RUNTIMES_INITIAL_SETUP_COMPILER_RT_LIBS

$(eval $(cmake-package))
