################################################################################
#
# llvm-runtimes
#
################################################################################

LLVM_RUNTIMES_VERSION = $(LLVM_PROJECT_VERSION)
LLVM_RUNTIMES_SITE = $(LLVM_PROJECT_SITE)
LLVM_RUNTIMES_SOURCE = $(LLVM_PROJECT_SOURCE)
LLVM_RUNTIMES_DL_SUBDIR = llvm-project
LLVM_RUNTIMES_LICENSE = Apache-2.0 with exceptions, NCSA, MIT
LLVM_RUNTIMES_LICENSE_FILES = LICENSE.TXT
LLVM_RUNTIMES_CPE_ID_VENDOR = llvm
LLVM_RUNTIMES_SUPPORTS_IN_SOURCE_BUILD = NO
LLVM_RUNTIMES_INSTALL_STAGING = YES
LLVM_RUNTIMES_SUBDIR = runtimes
LLVM_RUNTIMES_CMAKE_BACKEND = ninja

LLVM_RUNTIMES_DEPENDENCIES = host-clang host-lld

ifeq ($(BR2_TOOLCHAIN_BUILDROOT_LLVM),y)
LLVM_RUNTIMES_ADD_TOOLCHAIN_DEPENDENCY = NO
LLVM_RUNTIMES_DEPENDENCIES += musl llvm-runtimes-initial
endif

LLVM_RUNTIMES_LIST =
ifeq ($(BR2_PACKAGE_LLVM_RUNTIMES_COMPILER_RT),y)
LLVM_RUNTIMES_LIST += compiler-rt
endif
ifeq ($(BR2_PACKAGE_LLVM_RUNTIMES_LIBUNWIND),y)
LLVM_RUNTIMES_LIST += libunwind
endif
ifeq ($(BR2_PACKAGE_LLVM_RUNTIMES_LIBCXXABI),y)
LLVM_RUNTIMES_LIST += libcxxabi
endif
ifeq ($(BR2_PACKAGE_LLVM_RUNTIMES_LIBCXX),y)
LLVM_RUNTIMES_LIST += libcxx
endif

LLVM_RUNTIMES_CONF_OPTS = \
	-DLLVM_ENABLE_RUNTIMES="$(subst $(space),;,$(LLVM_RUNTIMES_LIST))" \
	-DLLVM_NATIVE_TOOL_DIR=$(HOST_DIR)/bin \
	-DLLVM_USE_HOST_TOOLS=ON \
	-DLLVM_DEFAULT_TARGET_TRIPLE=$(GNU_TARGET_NAME) \
	-DLLVM_BUILTIN_TARGETS=$(GNU_TARGET_NAME) \
	-DLLVM_RUNTIME_TARGETS=$(GNU_TARGET_NAME) \
	-DLLVM_HOST_TRIPLE=$(GNU_TARGET_NAME) \
	-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
	-DCOMPILER_RT_DEFAULT_TARGET_TRIPLE=$(GNU_TARGET_NAME) \
	-DCOMPILER_RT_CXX_LIBRARY=libcxx \
	-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
	-DCOMPILER_RT_USE_LLVM_UNWINDER=ON \
	-DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
	-DSANITIZER_CXX_ABI=libcxxabi \
	-DLIBCXXABI_USE_COMPILER_RT=ON \
	-DLIBCXXABI_USE_LLVM_UNWINDER=ON \
	-DLIBCXX_USE_COMPILER_RT=ON \
	-DLIBUNWIND_USE_COMPILER_RT=ON \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_ENABLE_ASSERTIONS=OFF \
	-DLLVM_ENABLE_BACKTRACES=OFF \
	-DLLVM_ENABLE_THREADS=ON \
	-DLLVM_ENABLE_ZLIB=OFF \
	-DLLVM_ENABLE_PIC=ON \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_DOCS=OFF \
	-DLLVM_BUILD_TESTS=OFF \
	-DLLVM_BUILD_EXAMPLES=OFF \
	-DLLVM_BUILD_DOCS=OFF

# libc++ is part of this build, so avoid linking it when CMake checks the C++
# compiler during the LLVM internal toolchain bootstrap.
ifeq ($(BR2_TOOLCHAIN_BUILDROOT_LLVM),y)
LLVM_RUNTIMES_CONF_OPTS += \
	-DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) -nostdlib++"
endif

ifeq ($(BR2_TOOLCHAIN_USES_MUSL),y)
LLVM_RUNTIMES_CONF_OPTS += -DLIBCXX_HAS_MUSL_LIBC=ON
endif

ifeq ($(BR2_STATIC_LIBS),y)
LLVM_RUNTIMES_CONF_OPTS += \
	-DLIBUNWIND_ENABLE_SHARED=OFF \
	-DLIBCXXABI_ENABLE_SHARED=OFF \
	-DLIBCXX_ENABLE_SHARED=OFF
else
LLVM_RUNTIMES_CONF_OPTS += \
	-DLIBUNWIND_ENABLE_SHARED=ON \
	-DLIBCXXABI_ENABLE_SHARED=ON \
	-DLIBCXX_ENABLE_SHARED=ON
endif

define LLVM_RUNTIMES_SETUP_COMPILER_RT_LIBS
	mkdir -p $(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/lib
	ln -snf ../../../../$(GNU_TARGET_NAME)/sysroot/usr/lib/linux \
		$(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/lib/linux
	ln -snf ../../../../$(GNU_TARGET_NAME)/sysroot/usr/share \
		$(HOST_DIR)/lib/clang/$(LLVM_PROJECT_VERSION_MAJOR)/share
endef
LLVM_RUNTIMES_POST_INSTALL_STAGING_HOOKS += LLVM_RUNTIMES_SETUP_COMPILER_RT_LIBS

define HOST_LLVM_RUNTIMES_INSTALL_CMDS
	mkdir -p $(HOST_DIR)/lib/cmake/llvm/Modules
	cp -Rv $(@D)/runtimes/cmake/Modules/* $(HOST_DIR)/lib/cmake/llvm
endef

$(eval $(cmake-package))
$(eval $(host-generic-package))
